# Basic CI for doing testing in python 3.6 with pytest

image: harbor.containers.wurnet.nl/proxy-cache/library/python:3.6

before_script:       # This job runs in the build stage, which runs first.
    - python --version
    - python -m pip install --upgrade pip
    - pip install -e .[dev]
    - pip list

stages:          # List of stages for jobs, and their order of execution
  - test

unit-test-job:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  script:
    - pytest --cov --cov-report term --cov-report xml
